#!/usr/bin/env bash

# take all the cache and remove useless packages
sudo pacman -Sc
sudo pacman -Scc
paccache -r
sudo pacman -Rns $(pacman -Qtdq)

# list cache 
sudo du -sh ~/.cache/
rm -rf ~/.cache/*