#!/bin/sh

dir_icons="/usr/local/bin/icons"

cur_vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( "$SINK" + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

vol_quiet=33
vol_loud=66

if [ "$cur_vol" -le "$vol_quiet" ]; then
    dunstify -a "Volume" \
    "Volume" \
    "Current volume is $cur_vol%" \
    -r 100 \
    -i $dir_icons/volume.svg
    fi
if [ "$cur_vol" -gt "$vol_quiet" ] && [ "$cur_vol" -le "$vol_loud" ]; then
    dunstify -a "Volume" \
    "Volume" \
    "Current volume is $cur_vol%" \
    -r 100 \
    -i $dir_icons/volume-1.svg
    fi
if [ "$cur_vol" -gt "$vol_loud" ]; then
    dunstify -a "Volume" \
    "Volume" \
    "Current volume is $cur_vol%" \
    -r 100 \
    -i $dir_icons/volume-2.svg
fi